version: '3'

services:
  civis-lab:
    build: ./
    image: civis-lab
    container_name: civis-lab
    volumes:
     - ../:/app
    ports:
      - "8888:8888"
    environment:
      - DEV=1
      - POSTGRES_URI=postgres://ita:secret@postgres:5432/ita
      - REDSHIFT_URI=postgres://ita:secret@redshift:5432/ita
    command: "jupyter-lab --no-browser --ip=\"*\" --allow-root --port=8888 --NotebookApp.notebook_dir=/app --NotebookApp.terminado_settings='{\"shell_command\": [\"bash\"]}' --LabApp.token=\"\" --LabApp.password=\"\""
  civis-voila:
    build: ./
    image: civis-voila
    container_name: civis-voila
    volumes:
     - ../:/app
    ports:
      - "3838:3838"
    environment:
      - DEV=1
      - CIVIS_SERVICE_ID=1
      - MY_AWS_USERNAME=${AWS_ACCESS_KEY_ID}
      - MY_AWS_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - REPO_PATH_DIR=${REPO_PATH_DIR}
  # Use the official postgis image for postgres
  postgres:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=ita
      - POSTGRES_PASSWORD=secret
  # Simulate redshift with postgis image as well
  redshift:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=ita
      - POSTGRES_PASSWORD=secret
